# Generated by Django 3.2.9 on 2022-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default=False, max_length=600)),
                ('dish', models.CharField(default=False, max_length=400)),
            ],
        ),
    ]
