# Generated by Django 3.2.9 on 2022-01-16 11:38

from django.db import migrations, models
class Migration(migrations.Migration):    
    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdish',
            name='star',
            field=models.CharField(default=False, max_length=800),
        ),
    ]
