# Generated by Django 3.2.9 on 2022-01-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20220102_1230'),
        ('reviews', '0002_rename_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dishes.dish'),
        ),
    ]
