# Generated by Django 3.2.9 on 2022-01-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0002_auto_20220102_1230'),
        ('reviews', '0003_review_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='review',
            name='post',
        ),
        migrations.AddField(
            model_name='review',
            name='dish_select',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dishes.dish'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
