# Generated by Django 3.2.9 on 2022-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220115_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
