# Generated by Django 3.2.9 on 2022-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_dish_select_review_select_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='select_dish',
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(default='Your thoughts', max_length=600),
        ),
    ]
