# Generated by Django 3.2.9 on 2022-01-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20220102_1230'),
        ('reviews', '0013_auto_20220116_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdish',
            name='select_dish',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dishes.dish'),
        ),
    ]
