# Generated by Django 3.2.9 on 2022-01-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_reviewdish_select_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdish',
            name='select_dish',
        ),
    ]
