# Generated by Django 3.2.9 on 2022-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_remove_reviewdish_select_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdish',
            name='dish',
            field=models.CharField(default=False, max_length=400),
        ),
    ]
